pipeline {
    agent any

    tools {
        jdk 'jdk-21' 
    }

    environment {
        DOCKER_PASSWORD = credentials("docker_password")
        GITHUB_TOKEN = credentials("github_token")
    }

    stages {
        stage('Build & Test') {
            steps {
                sh './gradlew clean build'
            }
        }

        stage('Tag image') {
            steps {
                script {
                    sh(script: 'git fetch --tags', returnStdout: true).trim()

                    sh([script: 'git fetch --tag', returnStdout: true]).trim()
                    env.MAJOR_VERSION = sh([script: 'git tag | sort --version-sort | tail -1 | cut -d . -f 1', returnStdout: true]).trim()
                    env.MINOR_VERSION = sh([script: 'git tag | sort --version-sort | tail -1 | cut -d . -f 2', returnStdout: true]).trim()
                    env.PATCH_VERSION = sh([script: 'git tag | sort --version-sort | tail -1 | cut -d . -f 3', returnStdout: true]).trim()
                    env.IMAGE_TAG = "${env.MAJOR_VERSION}.\$((${env.MINOR_VERSION} + 1)).${env.PATCH_VERSION}"
                }
            }
        }

        stage('Tag and Push Git Release') {
            steps {
            sh "git tag ${env.IMAGE_TAG}"
            sh "git push https://$GITHUB_TOKEN@github.com/Team-Code-Girls/service.git ${env.IMAGE_TAG}"
            }
        }
        // stage('Start App and DB Containers') {
        //   steps {
        //      sh "IMAGE_TAG=${env.IMAGE_TAG} docker compose up -d hello mongo"
        //         }
        // }
        stage('Run Integration Tests') {
            steps {
              sh './gradlew testIT'
                  }
       }
    }
}
